(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c="Traductor de Google",e=this||self;function f(a,l){a=a.split(".");var b=e;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===l?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=l}var g=/^[\w+/_-]+[=]{0,2}$/,h=null;function k(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&g.test(a)?a:""}function m(a){return a};var n={0:"Traducir",1:"Cancelar",2:"Cerrar",3:function(a){return"Google ha traducido esta p\u00e1gina autom\u00e1ticamente al "+(a+".")},4:function(a){return"Traducido al: "+a},5:"Error: el servidor no ha podido completar la solicitud. Vuelve a intentarlo m\u00e1s tarde.",6:"M\u00e1s informaci\u00f3n",7:function(a){return"Con la tecnolog\u00eda de "+a},8:c,9:"Traducci\u00f3n en curso",10:function(a){return"\u00bfQuieres traducir esta p\u00e1gina al "+(a+"TARGET_LANGUAGE con el Traductor de Google?")},
11:function(a){return"Ver esta p\u00e1gina en: "+a},12:"Mostrar texto original",13:"El contenido de este archivo local se enviar\u00e1 a Google para traducirlo con una conexi\u00f3n segura.",14:"El contenido de esta p\u00e1gina segura se enviar\u00e1 a Google para traducirlo con una conexi\u00f3n segura.",15:"El contenido de esta p\u00e1gina de intranet se enviar\u00e1 a Google para traducirlo con una conexi\u00f3n segura.",16:"Seleccionar idioma",17:function(a){return"Desactivar traducci\u00f3n del "+
a},18:function(a){return"Desactivar para: "+a},19:"Siempre oculto",20:"Texto original:",21:"Sugiere una traducci\u00f3n mejor",22:"Enviar",23:"Traducir todo",24:"Restaurar todo",25:"Cancelar todo",26:"Traducir secciones a mi idioma",27:function(a){return"Traducir todo al "+a},28:"Mostrar idiomas originales",29:"Opciones",30:"Desactivar la traducci\u00f3n en este sitio",31:null,32:"Mostrar traducciones alternativas",33:"Haz clic en las palabras anteriores para obtener traducciones alternativas.",34:"Usar",
35:"Pulsa May\u00fas y arrastra las palabras para cambiar el orden.",36:"Haz clic para obtener traducciones alternativas.",37:"Mant\u00e9n pulsada la tecla May\u00fas y, a continuaci\u00f3n, haz clic en las palabras y arr\u00e1stralas para cambiar el orden.",38:"Gracias por proponer una traducci\u00f3n al Traductor de Google.",39:"Administrar la traducci\u00f3n de este sitio",40:"Haz clic en una palabra para obtener traducciones alternativas o doble clic para editar las traducciones directamente.",
41:"Texto original",42:c,43:"Traducir",44:"Se ha enviado tu correcci\u00f3n.",45:"Error: no se admite el idioma de la p\u00e1gina web.",46:"Widget de idiomas del Traductor"};var p;function q(a,l){this.g=l===r?a:""}q.prototype.toString=function(){return this.g+""};var r={};var t=window.google&&google.translate&&google.translate._const;
if(t){var u;a:{for(var v=[],w=[""],x=0;x<w.length;++x){var y=w[x].split(","),z=y[0];if(z){var A=Number(y[1]);if(!(!A||.1<A||0>A)){var B=Number(y[2]),C=new Date,D=1E4*C.getFullYear()+100*(C.getMonth()+1)+C.getDate();!B||B<D||v.push({version:z,ratio:A,h:B})}}}var E=0,F=window.location.href.match(/google\.translate\.element\.random=([\d\.]+)/),G=Number(F&&F[1])||Math.random();for(x=0;x<v.length;++x){var H=v[x];E+=H.ratio;if(1<=E)break;if(G<E){u=H.version;break a}}u="TE_20210224_00"}var I="/element/%s/e/js/element/element_main.js".replace("%s",
u);if("0"==u){var J=" element %s e js element element_main.js".split(" ");J[J.length-1]="main_es.js";I=J.join("/").replace("%s",u)}if(t._cjlc)t._cjlc(t._pas+t._pah+I);else{var K=t._pas+t._pah+I,L,M="SCRIPT",N=document;M=String(M);"application/xhtml+xml"===N.contentType&&(M=M.toLowerCase());L=N.createElement(M);L.type="text/javascript";L.charset="UTF-8";var O,P;if(void 0===p){var Q=null,R=e.trustedTypes;if(R&&R.createPolicy){try{Q=R.createPolicy("goog#html",{createHTML:m,createScript:m,createScriptURL:m})}catch(a){e.console&&
e.console.error(a.message)}p=Q}else p=Q}var S=(P=p)?P.createScriptURL(K):K;O=new q(S,r);L.src=O instanceof q&&O.constructor===q?O.g:"type_error:TrustedResourceUrl";var T;var U=L.ownerDocument&&L.ownerDocument.defaultView;U&&U!=e?T=k(U.document):(null===h&&(h=k(e.document)),T=h);T&&L.setAttribute("nonce",T);var V=document.getElementsByTagName("head")[0];V||(V=document.body.parentNode.appendChild(document.createElement("head")));V.appendChild(L)}f("google.translate.m",n);f("google.translate.v",u)};}).call(window)
